version: "3.8"
services:
  client:
    build: ./Frontend
    container_name: clientapp_c
    ports:
      - "3000:3000"
    volumes:
      - ./Frontend:/app
      - ./app/node_modules
    stdin_open: true
    tty: true
  server:
    build: ./Backend
    container_name: serverapp_c
    ports:
      - "5000:5000"
    volumes:
      - ./Backend:/app
      - ./app/node_modules